#!/usr/bin/env python
"""One-shot: read qpose14's archive.zip, repack as emir_flatpack.

archive layout (single zip member 'p', store-only):
  brotli(  <III header (n_mask, n_model, n_pose)>
         + raw AV1 .obu mask bytes
         + flat-binary model weights (no pickle, no names, no shapes)
         + raw quantized 6-D pose bytes )

The decoder rebuilds the state-dict from a fixed schema baked into inflate.py.
"""
import io
import os
import struct
import sys
import zipfile
from pathlib import Path

import brotli
import torch

REPO = Path(__file__).resolve().parents[2]
# The 287,573-byte qpose14 archive. Set QPOSE14_ARCHIVE env var to override
# (e.g. point at a local copy you downloaded from
# https://github.com/user-attachments/files/27206870/archive.zip)
QPOSE14_ARCHIVE = Path(os.environ.get(
    "QPOSE14_ARCHIVE",
    REPO / "submissions" / "qpose14_archive.zip",
))
OUT_DIR = Path(__file__).resolve().parent
OUT_ARCHIVE = OUT_DIR / "archive.zip"
SCHEMA_OUT = OUT_DIR / "_schema.py"


def extract_qpose14_streams():
    """Pull the three brotli streams out of qpose14's single zip member."""
    p = zipfile.ZipFile(QPOSE14_ARCHIVE).read("p")
    mask_br  = p[:219472]
    model_br = p[219472:219472 + 66841]
    pose_br  = p[219472 + 66841:]
    return brotli.decompress(mask_br), brotli.decompress(model_br), brotli.decompress(pose_br)


def build_schema_and_flat_model(raw_model_bytes: bytes):
    """Walk torch.load() output once, emit (schema, flat_bytes)."""
    data = torch.load(io.BytesIO(raw_model_bytes), map_location="cpu", weights_only=False)
    block_size = int(data["__block_size__"])
    codebook   = data["__codebook__"].tolist()
    assert block_size == 32
    assert codebook == [0.0, 0.5, 1.0, 1.5, 2.0, 3.0, 4.0, 6.0]

    quantized_schema = []  # list of (name, kind, weight_shape, has_bias)
    dense_schema     = []  # list of (name, shape)
    flat = bytearray()

    for name, rec in data["quantized"].items():
        kind = rec["weight_kind"]
        shape = list(rec["weight_shape"])
        has_bias = rec.get("bias_fp16") is not None
        quantized_schema.append((name, kind, shape, has_bias))

        if kind == "fp4_packed":
            flat += rec["packed_weight"].numpy().tobytes()
            flat += rec["scales_fp16"].numpy().tobytes()
        elif kind == "fp16":
            flat += rec["weight_fp16"].numpy().tobytes()
        else:
            raise RuntimeError(f"unknown kind {kind}")

        if has_bias:
            flat += rec["bias_fp16"].numpy().tobytes()

    for name, t in data["dense_fp16"].items():
        dense_schema.append((name, list(t.shape)))
        flat += t.numpy().tobytes()

    return quantized_schema, dense_schema, bytes(flat)


def write_schema_module(quantized, dense):
    lines = ["# auto-generated by repack.py — do not edit",
             "QUANTIZED_SCHEMA = [",
             *(f"  ({name!r}, {kind!r}, {tuple(shape)}, {has_bias!r})," for (name, kind, shape, has_bias) in quantized),
             "]",
             "",
             "DENSE_SCHEMA = [",
             *(f"  ({name!r}, {tuple(shape)})," for (name, shape) in dense),
             "]",
             ""]
    SCHEMA_OUT.write_text("\n".join(lines))


def best_brotli(payload_pieces):
    """Try all orderings of the three streams, return smallest brotli output."""
    from itertools import permutations
    best = None
    for order in permutations(payload_pieces.keys()):
        # header lists lengths in the FIXED order mask, model, pose so the
        # decoder can split — but the brotli input order can vary.
        n_mask  = len(payload_pieces["mask"])
        n_model = len(payload_pieces["model"])
        n_pose  = len(payload_pieces["pose"])
        hdr = struct.pack("<III", n_mask, n_model, n_pose)
        # encode order tag in 1 byte after header
        order_tag = "".join(o[0] for o in order)  # e.g. "pmm"
        order_byte = {"mmp":0, "mpm":1, "mpp":2,
                      "mmm":0, "pmm":3, "pmp":4, "ppm":5,
                      "mpm":1}.get(order_tag, 0)
        # simpler: hardcode order indices
        ORDER_INDEX = {("mask","model","pose"):0,
                       ("mask","pose","model"):1,
                       ("model","mask","pose"):2,
                       ("model","pose","mask"):3,
                       ("pose","mask","model"):4,
                       ("pose","model","mask"):5}
        if order not in ORDER_INDEX:
            continue
        order_byte = ORDER_INDEX[order]
        body = b"".join(payload_pieces[k] for k in order)
        plain = bytes([order_byte]) + hdr + body
        compressed = brotli.compress(plain, quality=11, mode=brotli.MODE_GENERIC)
        if best is None or len(compressed) < best[0]:
            best = (len(compressed), order, compressed)
    return best


def main():
    print(f"[flatpack] reading {QPOSE14_ARCHIVE}")
    raw_mask, raw_model, raw_pose = extract_qpose14_streams()
    print(f"[flatpack] raw streams: mask={len(raw_mask):,} model={len(raw_model):,} pose={len(raw_pose):,}")

    quantized, dense, flat_model = build_schema_and_flat_model(raw_model)
    print(f"[flatpack] flat model: {len(flat_model):,} bytes (vs raw model.pt {len(raw_model):,})")
    write_schema_module(quantized, dense)
    print(f"[flatpack] wrote {SCHEMA_OUT}")

    pieces = {"mask": raw_mask, "model": flat_model, "pose": raw_pose}
    size, order, compressed = best_brotli(pieces)
    print(f"[flatpack] best brotli: {size:,} bytes (order={order})")

    with zipfile.ZipFile(OUT_ARCHIVE, "w", compression=zipfile.ZIP_STORED, strict_timestamps=False) as z:
        z.writestr("p", compressed)
    final_size = OUT_ARCHIVE.stat().st_size
    print(f"[flatpack] archive.zip = {final_size:,} bytes")

    qpose_size = QPOSE14_ARCHIVE.stat().st_size
    print(f"[flatpack] saved {qpose_size - final_size:,} bytes vs qpose14 ({qpose_size:,})")
    score_delta = 25 * (qpose_size - final_size) / 37545489
    print(f"[flatpack] expected score delta vs qpose14: {-score_delta:+.5f}")


if __name__ == "__main__":
    main()
